### ISSUE TITLE
When logger is disabled, it would trigger a panic:

### ISSUE THREAD

**Issue by stevapple** [USTC-vlab/sshmux#13]
It looks like when logger is disabled, it would trigger a panic:

```console
Aug 24 19:29:00 web sshmux-pr12[3869518]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 24 19:29:00 web sshmux-pr12[3869518]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d1f4f]
Aug 24 19:29:00 web sshmux-pr12[3869518]: goroutine 8 [running]:
Aug 24 19:29:00 web sshmux-pr12[3869518]: log/slog.(*Logger).clone(...)
Aug 24 19:29:00 web sshmux-pr12[3869518]:         log/slog/logger.go:117
Aug 24 19:29:00 web sshmux-pr12[3869518]: log/slog.(*Logger).With(0x0, {0xc000109f40, 0x3, 0x3})
Aug 24 19:29:00 web sshmux-pr12[3869518]:         log/slog/logger.go:131 +0x4f
Aug 24 19:29:00 web sshmux-pr12[3869518]: main.(*Server).handler(0xc00011a2c0, {0x80d198, 0xc000052108})
Aug 24 19:29:00 web sshmux-pr12[3869518]:         github.com/USTC-vlab/sshmux/sshmux.go:155 +0x325
Aug 24 19:29:00 web sshmux-pr12[3869518]: created by main.(*Server).serve in goroutine 7
Aug 24 19:29:00 web sshmux-pr12[3869518]:         github.com/USTC-vlab/sshmux/sshmux.go:136 +0x125
```

_Originally posted by @taoky in https://github.com/USTC-vlab/sshmux/issues/12#issuecomment-2308361814_

**Comment by stevapple** [comment]
Solved by #14
